-- Add client_id column to search_queue table
--
-- client_id is a UUID generated by the frontend before submitting a search.
-- This creates an unbreakable link between frontend popup tracking and backend
-- search processing, preventing orphaned popups when matching by query fails.
--
-- The client_id is included in all WebSocket events related to a search,
-- allowing the frontend to reliably match events to the correct popup.

ALTER TABLE search_queue ADD COLUMN client_id TEXT;

-- Index for looking up by client_id (if needed for debugging)
CREATE INDEX idx_search_queue_client_id ON search_queue(client_id);
